### ISSUE TITLE
index.phpの表示画面の作成

### ISSUE THREAD

**Issue by minami1059** [KazukiYokoyama/PHP_Study#2]
index.phpにアクセスした際に、ダミーの投稿者リストを表示させてください。

**Comment by utugishinra** [comment]
了解しました

**Comment by KazukiYokoyama** [comment]
横から申し訳ない。
最新のCommitでindex.phpにアクセスした場合はトップページを表示するようにしました。
（まだ、Blog Homeとでているだけですが…）
そちらを動作確認した後、この問題をCloseしてください。
